### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by davipatti**
I was following OS X install instructions. After `pip install dark-matter` and `pip install -r requirements.txt` I was getting:

```
(test-env) david ~> convert-blast-xml-to-json.py --help
Traceback (most recent call last):
  File "/Users/david/.virtualenvs/test-env/bin/convert-blast-xml-to-json.py", line 7, in <module>
    from dark.blast.conversion import XMLRecordsReader
  File "/Users/david/.virtualenvs/test-env/lib/python2.7/site-packages/dark/blast/conversion.py", line 13, in <module>
    from dark.alignments import Alignment, ReadAlignments
  File "/Users/david/.virtualenvs/test-env/lib/python2.7/site-packages/dark/alignments.py", line 3, in <module>
    from dark.taxonomy import LineageFetcher
  File "/Users/david/.virtualenvs/test-env/lib/python2.7/site-packages/dark/taxonomy.py", line 1, in <module>
    from dark.database import getDatabaseConnection
  File "/Users/david/.virtualenvs/test-env/lib/python2.7/site-packages/dark/database.py", line 3, in <module>
    from mysql import connector
ImportError: No module named mysql
```

### CODE REVIEW

**Comment by terrycojones** [comment]
Hi @davipatti - thanks for this :-)  Does that (`pip install mysql-connector-python`) actually work? It used not to. If so, great.  If not, you'll need to follow the steps at the end of the `install-dependencies.sh` script at the top level.

**Comment by davipatti** [comment]
Yeah, `pip install mysql-connector-python` seemed to work fine.

**Comment by terrycojones** [comment]
OK, that's good news. If you want to finish this off, can you also do these small things:

1. Increment the version number in `dark/__init__.py`
1. Add an entry to `CHANGELOG.md`
1. `git rm install-dependencies.sh`
1. In `.travis.yml` change the install line to just run `pip install -r requirements.txt`

Then commit & push your branch again. The Travis tests will automatically be run and we can see if this change works on all supported Python versions.  You'll see the Travis status on the pull request page (and also in #acorg) - it takes a few minutes to complete.

Thanks!

**Comment by terrycojones** [comment]
3.0.12 is now on PyPI. You should be able to upgrade to it via

```sh
$ pip install --no-cache-dir -U dark-matter
```

There's a command you can use to see what version you have installed:

```sh
$ dark-matter-version.py
3.0.12
```

Thanks again :-)

**Pull request merged**
